# Generated by Django 3.2.7 on 2021-10-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leap_years',
            name='year',
            field=models.IntegerField(),
        ),
    ]
