# Generated by Django 3.2.7 on 2021-10-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211028_0046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_view',
        ),
    ]
