# Generated by Django 3.2.7 on 2021-10-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_user_user_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leap_year',
            new_name='Leap_years',
        ),
    ]
